const products = [
  {
    id: 1,
    name: "Khóa học ReactJS",
    price: 800000,
    image: "https://cdn2.fptshop.com.vn/unsafe/150x0/filters:format(webp):quality(75)/acer_nitro_v_15_anv15_51_1_18385501dc.png",
    shortDesc: "Từ cơ bản đến nâng cao",
    fullDesc: "Học ReactJS qua dự án, kết hợp AI gợi ý lộ trình học.",
    rating: 4.8,
  },
  {
    id: 2,
    name: "Tiếng Anh giao tiếp",
    price: 1500000,
    image: "https://cdn2.fptshop.com.vn/unsafe/150x0/filters:format(webp):quality(75)/acer_nitro_v_15_anv15_51_1_18385501dc.png",
    shortDesc: "Luyện nói với người bản xứ",
    fullDesc: "Cam kết giao tiếp lưu loát sau 3 tháng, học qua Zoom.",
    rating: 4.9,
  },
  {
    id: 3,
    name: "Khóa học ReactJS",
    price: 800000,
    image: "https://cdn2.fptshop.com.vn/unsafe/150x0/filters:format(webp):quality(75)/acer_nitro_v_15_anv15_51_1_18385501dc.png",
    shortDesc: "Từ cơ bản đến nâng cao",
    fullDesc: "Học ReactJS qua dự án, kết hợp AI gợi ý lộ trình học.",
    rating: 4.8,
  },
  {
    id: 4,
    name: "Tiếng Anh giao tiếp",
    price: 1500000,
    image: "https://cdn2.fptshop.com.vn/unsafe/150x0/filters:format(webp):quality(75)/acer_nitro_v_15_anv15_51_1_18385501dc.png",
    shortDesc: "Luyện nói với người bản xứ",
    fullDesc: "Cam kết giao tiếp lưu loát sau 3 tháng, học qua Zoom.",
    rating: 4.9,
  },
  {
    id: 5,
    name: "Khóa học ReactJS",
    price: 800000,
    image: "https://cdn2.fptshop.com.vn/unsafe/150x0/filters:format(webp):quality(75)/acer_nitro_v_15_anv15_51_1_18385501dc.png",
    shortDesc: "Từ cơ bản đến nâng cao",
    fullDesc: "Học ReactJS qua dự án, kết hợp AI gợi ý lộ trình học.",
    rating: 4.8,
  },
  {
    id: 6,
    name: "Tiếng Anh giao tiếp",
    price: 1500000,
    image: "https://cdn2.fptshop.com.vn/unsafe/150x0/filters:format(webp):quality(75)/acer_nitro_v_15_anv15_51_1_18385501dc.png",
    shortDesc: "Luyện nói với người bản xứ",
    fullDesc: "Cam kết giao tiếp lưu loát sau 3 tháng, học qua Zoom.",
    rating: 4.9,
  },
  {
    id: 7,
    name: "Khóa học ReactJS",
    price: 800000,
    image: "https://cdn2.fptshop.com.vn/unsafe/150x0/filters:format(webp):quality(75)/acer_nitro_v_15_anv15_51_1_18385501dc.png",
    shortDesc: "Từ cơ bản đến nâng cao",
    fullDesc: "Học ReactJS qua dự án, kết hợp AI gợi ý lộ trình học.",
    rating: 4.8,
  },
  {
    id: 8,
    name: "Tiếng Anh giao tiếp",
    price: 1500000,
    image: "https://cdn2.fptshop.com.vn/unsafe/150x0/filters:format(webp):quality(75)/acer_nitro_v_15_anv15_51_1_18385501dc.png",
    shortDesc: "Luyện nói với người bản xứ",
    fullDesc: "Cam kết giao tiếp lưu loát sau 3 tháng, học qua Zoom.",
    rating: 4.9,
  },
];

export default products;
