const products = [
  {
    id: 1,
    name: "Khóa học ReactJS nâng cao",
    price: 1200000,
    image: "https://cdn-icons-png.flaticon.com/512/919/919851.png",
    shortDesc: "Xây dựng SPA chuyên nghiệp",
    fullDesc: "Học ReactJS nâng cao qua dự án thực tế, có hỗ trợ AI.",
    rating: 3,
  },
  {
    id: 2,
    name: "Khóa học Python căn bản",
    price: 900000,
    image: "https://cdn-icons-png.flaticon.com/512/1822/1822899.png",
    shortDesc: "Nhập môn lập trình Python",
    fullDesc: "Khóa học dành cho người mới bắt đầu, dễ hiểu.",
    rating: 4,
  },
  {
    id: 3,
    name: "Khóa học Data Science",
    price: 1800000,
    image: "https://cdn-icons-png.flaticon.com/512/1055/1055687.png",
    shortDesc: "Phân tích dữ liệu chuyên sâu",
    fullDesc: "Học cách khai thác dữ liệu, mô hình hóa và trực quan hóa.",
    rating: 4.8,
  },
  {
    id: 4,
    name: "Khóa học Tiếng Anh giao tiếp",
    price: 1500000,
    image: "https://cdn-icons-png.flaticon.com/512/197/197484.png",
    shortDesc: "Phát âm và hội thoại tự tin",
    fullDesc: "Luyện nói với giáo viên bản ngữ qua Zoom.",
    rating: 4.6,
  },
  {
    id: 5,
    name: "Khóa học Thiết kế UI/UX",
    price: 1300000,
    image: "https://cdn-icons-png.flaticon.com/512/2331/2331922.png",
    shortDesc: "Thiết kế giao diện chuyên nghiệp",
    fullDesc: "Tìm hiểu nguyên tắc thiết kế và thực hành dự án.",
    rating: 4,
  },
  {
    id: 6,
    name: "Khóa học JavaScript căn bản",
    price: 850000,
    image: "https://cdn-icons-png.flaticon.com/512/5968/5968292.png",
    shortDesc: "Học JS từ zero đến hero",
    fullDesc: "Nắm vững nền tảng JavaScript cho Web Development.",
    rating: 4.8,
  },
  {
    id: 7,
    name: "Khóa học Digital Marketing",
    price: 1400000,
    image: "https://cdn-icons-png.flaticon.com/512/3014/3014270.png",
    shortDesc: "Chiến lược marketing hiện đại",
    fullDesc: "Thực hành chạy quảng cáo và phân tích thị trường.",
    rating: 4.5,
  },
  {
    id: 8,
    name: "Khóa học Blockchain cơ bản",
    price: 2000000,
    image: "https://cdn-icons-png.flaticon.com/512/919/919826.png",
    shortDesc: "Khám phá công nghệ Blockchain",
    fullDesc: "Tìm hiểu cách hoạt động và ứng dụng Blockchain.",
    rating: 3.5,
  },
  // Bổ sung thêm
  {
    id: 9,
    name: "Khóa học AWS Cloud",
    price: 1700000,
    image: "https://cdn-icons-png.flaticon.com/512/906/906175.png",
    shortDesc: "Triển khai và quản lý dịch vụ đám mây",
    fullDesc: "Học cách dùng AWS để xây dựng hạ tầng linh hoạt.",
    rating: 4.7,
  },
  {
    id: 10,
    name: "Khóa học Machine Learning",
    price: 2200000,
    image: "https://cdn-icons-png.flaticon.com/512/2913/2913465.png",
    shortDesc: "Thuật toán học máy cơ bản",
    fullDesc: "Áp dụng ML để dự đoán và phân loại dữ liệu.",
    rating: 4.9,
  },
  {
    id: 11,
    name: "Khóa học SEO cơ bản",
    price: 750000,
    image: "https://cdn-icons-png.flaticon.com/512/2659/2659361.png",
    shortDesc: "Tối ưu công cụ tìm kiếm",
    fullDesc: "Học cách tăng traffic tự nhiên cho website.",
    rating: 4.4,
  },
  {
    id: 12,
    name: "Khóa học Photoshop",
    price: 1100000,
    image: "https://cdn-icons-png.flaticon.com/512/888/888879.png",
    shortDesc: "Thiết kế hình ảnh chuyên nghiệp",
    fullDesc: "Học các kỹ thuật chỉnh sửa ảnh nâng cao.",
    rating: 4.5,
  },
  {
    id: 13,
    name: "Khóa học WordPress",
    price: 800000,
    image: "https://cdn-icons-png.flaticon.com/512/732/732212.png",
    shortDesc: "Tạo website nhanh với WordPress",
    fullDesc: "Xây dựng blog, cửa hàng online dễ dàng.",
    rating: 4.6,
  },
  {
    id: 14,
    name: "Khóa học DevOps",
    price: 1900000,
    image: "https://cdn-icons-png.flaticon.com/512/3075/3075977.png",
    shortDesc: "Tự động hóa quy trình phát triển",
    fullDesc: "Sử dụng Docker, Jenkins và Kubernetes hiệu quả.",
    rating: 4.7,
  },
  {
    id: 15,
    name: "Khóa học Android cơ bản",
    price: 1250000,
    image: "https://cdn-icons-png.flaticon.com/512/888/888857.png",
    shortDesc: "Phát triển ứng dụng Android",
    fullDesc: "Học lập trình app Android từ A-Z.",
    rating: 4.6,
  },
  {
    id: 16,
    name: "Khóa học Excel nâng cao",
    price: 700000,
    image: "https://cdn-icons-png.flaticon.com/512/732/732220.png",
    shortDesc: "Phân tích dữ liệu bằng Excel",
    fullDesc: "Sử dụng hàm nâng cao và PivotTable.",
    rating: 4.5,
  },
];

export default products;
